id = "yellowed"
name = "Yellowed"
version = "0.0.3"
schema_version = 1
authors = ["Gael Lopes Da Silva <gael.lopes-da-silva@outlook.fr>"]
description = "A yellow material theme for Zed"
repository = "https://github.com/gael-lopes-da-silva/YellowedZed"